### ISSUE TITLE
Question about ServerAdmin in httpd?

### ISSUE THREAD

**Issue by odunybrad** [selim13/docker-wordpress-apache#1]
Thanks for providing the container! 

I am doing a research aiming at finding issues in configuration files. After pulling the image we notice that `ServerAdmin` is set to `webmaster@localhost` in `/etc/apache2/sites-enabled/000-default.conf`.  

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#servername) recommends the following config:
*  `ServerAdmin`: "However, it's recommended to actually use an email address, since there are a lot of CGI scripts that make that assumption. "

Could you please provide a knob to specify the value of `ServerAdmin`?

**Comment by selim13** [comment]
Hello and sorry for the late response. Was on a long vacation.

I've added `APACHE_SERVER_ADMIN` environment variable for setting ServerAdmin as well as `APACHE_DOCUMENT_ROOT` for setting DocumentRoot.

But in general ServerAdmin is redundant here as neither apache nor wordpress use it by default.
